# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='shortcode',
            field=models.CharField(default='defaulturl', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
