# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0002_shorturl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
