# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 04:20
from __future__ import unicode_literals

import cutter.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0004_shorturl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(max_length=256, validators=[cutter.validators.validate_url, cutter.validators.validate_dot_com]),
        ),
    ]
